using System;
using System.Collections.Generic;
using UnityEngine;

namespace AuraXR
{
    /// <summary>
    /// Loads pre-computed SDF PCA embeddings (32-dim per HOT3D object) from JSON.
    /// Used by AuraXRInferenceManager to condition the LSTM model on object geometry.
    ///
    /// JSON: Resources/sdf_embeddings_unity.json (generated by src/sdf_utils.py)
    ///   { "items": [ { "name":"bowl", "bop_id":2, "embedding":[32 floats] }, ... ] }
    ///
    /// Usage:
    ///   float[] emb = sdfDb.GetEmbedding(bopId);  // 32-dim, zeros if unknown
    /// </summary>
    public class ObjectSDFDatabase : MonoBehaviour
    {
        [Tooltip("Drag sdf_embeddings_unity.json (from Resources/) here, or leave null to auto-load")]
        public TextAsset embeddingsJson;

        public const int EMBED_DIM = 32;

        private readonly Dictionary<int, float[]> _byBopId = new();
        private static readonly float[] _zeros = new float[EMBED_DIM];

        void Awake()
        {
            if (embeddingsJson == null)
                embeddingsJson = Resources.Load<TextAsset>("sdf_embeddings_unity");

            if (embeddingsJson != null)
                Load(embeddingsJson.text);
            else
                Debug.LogWarning("[AuraXR] ObjectSDFDatabase: sdf_embeddings_unity.json not found in Resources. SDF embeddings will be zero.");
        }

        private void Load(string jsonText)
        {
            var list = JsonUtility.FromJson<SDFEmbeddingList>(jsonText);
            if (list?.items == null)
            {
                Debug.LogError("[AuraXR] ObjectSDFDatabase: failed to parse sdf_embeddings_unity.json.");
                return;
            }
            foreach (var item in list.items)
            {
                if (item.embedding != null && item.embedding.Length == EMBED_DIM)
                    _byBopId[item.bop_id] = item.embedding;
            }
            Debug.Log($"[AuraXR] ObjectSDFDatabase: loaded {_byBopId.Count} embeddings.");
        }

        /// <summary>Returns 32-dim SDF embedding for a BOP object ID, or zeros if not found.</summary>
        public float[] GetEmbedding(int bopId)
        {
            return _byBopId.TryGetValue(bopId, out var emb) ? emb : _zeros;
        }

        public bool HasEmbedding(int bopId) => _byBopId.ContainsKey(bopId);

        [Serializable] private class SDFEmbeddingList { public SDFEmbeddingItem[] items; }
        [Serializable] private class SDFEmbeddingItem { public string name; public int bop_id; public float[] embedding; }
    }
}
