"""Summarize Unity E0/E1 experience telemetry CSVs.

Usage after recording one or more SessionDataLogger CSV files:

    .venv/bin/python3 src/summarize_experience_replay.py \
        --csv path/to/e0.csv path/to/e1.csv \
        --out results/experience/e0_e1_replay.json \
        --notes results/experience/e0_e1_notes.md
"""

from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path
from statistics import mean

import numpy as np


def _as_float(row: dict[str, str], key: str, default: float = 0.0) -> float:
    try:
        return float(row.get(key, default))
    except (TypeError, ValueError):
        return default


def _as_int(row: dict[str, str], key: str, default: int = 0) -> int:
    try:
        return int(float(row.get(key, default)))
    except (TypeError, ValueError):
        return default


def summarize_csv(path: Path) -> dict:
    rows_by_label: dict[str, list[dict[str, str]]] = defaultdict(list)
    with path.open(newline="") as f:
        for row in csv.DictReader(f):
            rows_by_label[row.get("session_label", "unknown")].append(row)

    summaries = {}
    for label, rows in rows_by_label.items():
        left_delta = np.array([_as_float(r, "left_angle_delta_deg") for r in rows], dtype=float)
        right_delta = np.array([_as_float(r, "right_angle_delta_deg") for r in rows], dtype=float)
        left_jerk = np.array([_as_float(r, "left_angle_jerk_deg") for r in rows], dtype=float)
        right_jerk = np.array([_as_float(r, "right_angle_jerk_deg") for r in rows], dtype=float)
        left_dist = np.array([_as_float(r, "left_obj_distance_m", -1.0) for r in rows], dtype=float)
        right_dist = np.array([_as_float(r, "right_obj_distance_m", -1.0) for r in rows], dtype=float)
        left_switches = sum(_as_int(r, "left_object_switched") for r in rows)
        right_switches = sum(_as_int(r, "right_object_switched") for r in rows)
        timestamps = [_as_float(r, "timestamp") for r in rows]
        duration_s = max(timestamps) - min(timestamps) if len(timestamps) >= 2 else 0.0

        summaries[label] = {
            "source_csv": str(path),
            "row_count": len(rows),
            "duration_s": duration_s,
            "object_switch_count": {
                "left": int(left_switches),
                "right": int(right_switches),
                "per_minute": float((left_switches + right_switches) / max(duration_s / 60.0, 1e-6)),
            },
            "angle_delta_deg": {
                "left_p95": float(np.percentile(left_delta, 95)) if len(left_delta) else None,
                "right_p95": float(np.percentile(right_delta, 95)) if len(right_delta) else None,
                "mean_both": float(mean([left_delta.mean(), right_delta.mean()])) if len(left_delta) and len(right_delta) else None,
            },
            "angle_jerk_deg": {
                "left_p95": float(np.percentile(left_jerk, 95)) if len(left_jerk) else None,
                "right_p95": float(np.percentile(right_jerk, 95)) if len(right_jerk) else None,
                "mean_both": float(mean([left_jerk.mean(), right_jerk.mean()])) if len(left_jerk) and len(right_jerk) else None,
            },
            "object_distance_m": {
                "left_valid_mean": float(left_dist[left_dist >= 0].mean()) if np.any(left_dist >= 0) else None,
                "right_valid_mean": float(right_dist[right_dist >= 0].mean()) if np.any(right_dist >= 0) else None,
            },
        }
    return summaries


def write_notes(out: Path, summary: dict) -> None:
    lines = [
        "# E0/E1 Experience Replay Notes",
        "",
        "Generated by `src/summarize_experience_replay.py`.",
        "",
        "## Summary",
        "",
        "| Label | Duration | Switch/min | Delta p95 L/R | Jerk p95 L/R |",
        "|---|---:|---:|---:|---:|",
    ]
    for label, s in summary.items():
        delta = s["angle_delta_deg"]
        jerk = s["angle_jerk_deg"]
        lines.append(
            f"| {label} | {s['duration_s']:.1f}s | "
            f"{s['object_switch_count']['per_minute']:.1f} | "
            f"{delta['left_p95']:.2f}/{delta['right_p95']:.2f} | "
            f"{jerk['left_p95']:.2f}/{jerk['right_p95']:.2f} |"
        )
    lines.extend([
        "",
        "## Manual Observations",
        "",
        "- Fill after watching the capture: where does the hand jump?",
        "- Does it close before user intent?",
        "- Does it penetrate or float near objects?",
        "- Is release abrupt?",
        "",
    ])
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--csv", nargs="+", type=Path, required=True)
    p.add_argument("--out", type=Path, default=Path("results/experience/e0_e1_replay.json"))
    p.add_argument("--notes", type=Path, default=Path("results/experience/e0_e1_notes.md"))
    return p.parse_args()


def main() -> None:
    args = parse_args()
    combined = {}
    for path in args.csv:
        for label, summary in summarize_csv(path).items():
            key = label
            if key in combined:
                key = f"{label}:{path.stem}"
            combined[key] = summary

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(combined, indent=2))
    write_notes(args.notes, combined)
    print(args.out)
    print(args.notes)


if __name__ == "__main__":
    main()
